<br>

# Introdução

In [13]:
import pandas as pd

In [14]:
from paths import *

In [15]:
URL = 'https://legislacao.fazenda.sp.gov.br/Paginas/ValoresDaUFESP.aspx'
dfs = pd.read_html(URL)

In [16]:
df = dfs[2]
df

,PERÍODO,VALOR EM R$,BASE LEGAL
0,de 01/01/2022 A 31/12/2022,"​31,97","​Comunicado DICAR-89/21, de 17-12-2021"
1,​de 01/01/2021 A 31/12/2021,"​29,09","Comunicado DICAR-86/20, de 17-12-2020"
2,​de 01/01/2020 A 31/12/2020,"​27,61","​Comunicado DICAR-83/19, de 18-12-2019"
3,​de 01/01/2019 A 31/12/2019,"​26,53","Comunicado DA-89/18, de 18-12-2018"
4,de 01/01/2018 A 31/12/2018,2570,"Comunicado DA-96/17, de 20-12-2017"
5,de 01/01/2017 A 31/12/2017,2507,"Comunicado DA-98/16, de 19-12-2016"
6,de 01/01/2016 A 31/12/2016,2355,"Comunicado DA-98/15, de 17-12-2015"
7,de 01/01/2015 A 31/12/2015,2125,"Comunicado DA-80/14, de 16-12-2014"
8,de 01/01/2014 A 31/12/2014,2014,"Comunicado DA-75/13, de 18-12-2013"
9,de 01/01/2013 A 31/12/2013,1937,"Comunicado DA-90/12, de 18-12-2012"
10,de 01/01/2012 A 31/12/2012,1844,"Comunicado DA-87/11, de 19-12-2011"
11,de 01/01/2011 A 31/12/2011,1745,"Comunicado DA-88/10, de 17-12-2010"
12,de 01/01/2010 A 31/12/2010,1642,"Comunicado DA-55/09, de 17-12-2009"
13,de 01/01/2009 A 31/12/2009,1585,"Comunicado DA-52/08, de 17-12-2008"
14,de 01/01/2008 A 31/12/2008,1488,"Comunicado DA-53/07, de 19-12-2007"
15,de 01/01/2007 A 31/12/2007,1423,"Comunicado DA-51/06, de 20-12-2006"
16,de 01/01/2006 A 31/12/2006,1393,"Comunicado DA-57/05, de 20-12-2005"
17,de 01/01/2005 A 31/12/2005,1330,"Comunicado DA-50/04, de 20-12-2004"
18,de 01/01/2004 a 31/12/2004,1249,"Comunicado DA-39/03, de 18-12-2003"
19,de 01/01/2003 a 31/12/2003,1149,"Comunicado DA-32/02, de 18-12-2002"
20,de 01/01/2002 a 31/12/2002,1052,"Comunicado DA-27/01, de 26-12-2001"
21,de 01/01/2001 a 31/12/2001,983,NaN
22,de 01/01/2000 a 31/12/2000,927,NaN
23,de 01/01/1999 a 31/12/1999,851,NaN
24,de 01/01/1998 a 31/12/1998,837,NaN
25,de 01/01/1997 a 31/12/1997,793,NaN

In [17]:
df.loc[:, 'VALOR EM R$'] = df['VALOR EM R$'].replace(',', '', regex=True)
df.loc[:, 'VALOR EM R$'] = df['VALOR EM R$'].replace('\u200b', '', regex=True)
df.loc[:, 'VALOR EM R$'] = df['VALOR EM R$'].astype(float)
df.loc[:, 'VALOR EM R$'] = df['VALOR EM R$'] / 100
df

,PERÍODO,VALOR EM R$,BASE LEGAL
0,de 01/01/2022 A 31/12/2022,31.97,"​Comunicado DICAR-89/21, de 17-12-2021"
1,​de 01/01/2021 A 31/12/2021,29.09,"Comunicado DICAR-86/20, de 17-12-2020"
2,​de 01/01/2020 A 31/12/2020,27.61,"​Comunicado DICAR-83/19, de 18-12-2019"
3,​de 01/01/2019 A 31/12/2019,26.53,"Comunicado DA-89/18, de 18-12-2018"
4,de 01/01/2018 A 31/12/2018,25.70,"Comunicado DA-96/17, de 20-12-2017"
5,de 01/01/2017 A 31/12/2017,25.07,"Comunicado DA-98/16, de 19-12-2016"
6,de 01/01/2016 A 31/12/2016,23.55,"Comunicado DA-98/15, de 17-12-2015"
7,de 01/01/2015 A 31/12/2015,21.25,"Comunicado DA-80/14, de 16-12-2014"
8,de 01/01/2014 A 31/12/2014,20.14,"Comunicado DA-75/13, de 18-12-2013"
9,de 01/01/2013 A 31/12/2013,19.37,"Comunicado DA-90/12, de 18-12-2012"
10,de 01/01/2012 A 31/12/2012,18.44,"Comunicado DA-87/11, de 19-12-2011"
11,de 01/01/2011 A 31/12/2011,17.45,"Comunicado DA-88/10, de 17-12-2010"
12,de 01/01/2010 A 31/12/2010,16.42,"Comunicado DA-55/09, de 17-12-2009"
13,de 01/01/2009 A 31/12/2009,15.85,"Comunicado DA-52/08, de 17-12-2008"
14,de 01/01/2008 A 31/12/2008,14.88,"Comunicado DA-53/07, de 19-12-2007"
15,de 01/01/2007 A 31/12/2007,14.23,"Comunicado DA-51/06, de 20-12-2006"
16,de 01/01/2006 A 31/12/2006,13.93,"Comunicado DA-57/05, de 20-12-2005"
17,de 01/01/2005 A 31/12/2005,13.30,"Comunicado DA-50/04, de 20-12-2004"
18,de 01/01/2004 a 31/12/2004,12.49,"Comunicado DA-39/03, de 18-12-2003"
19,de 01/01/2003 a 31/12/2003,11.49,"Comunicado DA-32/02, de 18-12-2002"
20,de 01/01/2002 a 31/12/2002,10.52,"Comunicado DA-27/01, de 26-12-2001"
21,de 01/01/2001 a 31/12/2001,9.83,NaN
22,de 01/01/2000 a 31/12/2000,9.27,NaN
23,de 01/01/1999 a 31/12/1999,8.51,NaN
24,de 01/01/1998 a 31/12/1998,8.37,NaN
25,de 01/01/1997 a 31/12/1997,7.93,NaN

In [18]:
df.loc[:, 'PERÍODO'] = df['PERÍODO'].replace('de ', '', regex=True)
df.loc[:, 'PERÍODO'] = df['PERÍODO'].replace(' a ', ' A ', regex=True)

df.loc[:, 'PERÍODO'] = df['PERÍODO'].replace('\u200b', '', regex=True)
df.loc[:, 'PERÍODO'] = df['PERÍODO'].replace('\xa0', ' ', regex=True)
df[['data_inicio', 'data_fim']] = df['PERÍODO'].str.split('A', 1, expand=True)

df.loc[:, 'data_inicio'] = df.loc[:, 'data_inicio'].str.strip()
df.loc[:, 'data_fim'] = df.loc[:, 'data_fim'].str.strip()

df.loc[:, 'data_inicio'] = pd.to_datetime(df['data_inicio'], format='%d/%m/%Y')
df.loc[:, 'data_fim'] = pd.to_datetime(df['data_fim'], format='%d/%m/%Y')

df.loc[:, 'ano_mes'] = pd.to_datetime(df['data_inicio']).dt.to_period('M')

df.rename({'VALOR EM R$': 'valor', 'BASE LEGAL': 'base_legal'},
          axis=1, inplace=True)

df = df[['data_inicio', 'data_fim', 'ano_mes', 'valor', 'base_legal']]
df

,data_inicio,data_fim,ano_mes,valor,base_legal
0,2022-01-01,2022-12-31,2022-01,31.97,"​Comunicado DICAR-89/21, de 17-12-2021"
1,2021-01-01,2021-12-31,2021-01,29.09,"Comunicado DICAR-86/20, de 17-12-2020"
2,2020-01-01,2020-12-31,2020-01,27.61,"​Comunicado DICAR-83/19, de 18-12-2019"
3,2019-01-01,2019-12-31,2019-01,26.53,"Comunicado DA-89/18, de 18-12-2018"
4,2018-01-01,2018-12-31,2018-01,25.70,"Comunicado DA-96/17, de 20-12-2017"
5,2017-01-01,2017-12-31,2017-01,25.07,"Comunicado DA-98/16, de 19-12-2016"
6,2016-01-01,2016-12-31,2016-01,23.55,"Comunicado DA-98/15, de 17-12-2015"
7,2015-01-01,2015-12-31,2015-01,21.25,"Comunicado DA-80/14, de 16-12-2014"
8,2014-01-01,2014-12-31,2014-01,20.14,"Comunicado DA-75/13, de 18-12-2013"
9,2013-01-01,2013-12-31,2013-01,19.37,"Comunicado DA-90/12, de 18-12-2012"
10,2012-01-01,2012-12-31,2012-01,18.44,"Comunicado DA-87/11, de 19-12-2011"
11,2011-01-01,2011-12-31,2011-01,17.45,"Comunicado DA-88/10, de 17-12-2010"
12,2010-01-01,2010-12-31,2010-01,16.42,"Comunicado DA-55/09, de 17-12-2009"
13,2009-01-01,2009-12-31,2009-01,15.85,"Comunicado DA-52/08, de 17-12-2008"
14,2008-01-01,2008-12-31,2008-01,14.88,"Comunicado DA-53/07, de 19-12-2007"
15,2007-01-01,2007-12-31,2007-01,14.23,"Comunicado DA-51/06, de 20-12-2006"
16,2006-01-01,2006-12-31,2006-01,13.93,"Comunicado DA-57/05, de 20-12-2005"
17,2005-01-01,2005-12-31,2005-01,13.30,"Comunicado DA-50/04, de 20-12-2004"
18,2004-01-01,2004-12-31,2004-01,12.49,"Comunicado DA-39/03, de 18-12-2003"
19,2003-01-01,2003-12-31,2003-01,11.49,"Comunicado DA-32/02, de 18-12-2002"
20,2002-01-01,2002-12-31,2002-01,10.52,"Comunicado DA-27/01, de 26-12-2001"
21,2001-01-01,2001-12-31,2001-01,9.83,NaN
22,2000-01-01,2000-12-31,2000-01,9.27,NaN
23,1999-01-01,1999-12-31,1999-01,8.51,NaN
24,1998-01-01,1998-12-31,1998-01,8.37,NaN
25,1997-01-01,1997-12-31,1997-01,7.93,NaN

In [19]:
df.to_csv(
    data_path / 'ufesp.csv',
    index=False,
)

In [29]:
df = pd.read_csv(
    data_path / 'ufesp.csv',
    parse_dates=['data_inicio', 'data_fim', 'ano_mes']
)
df.loc[:, 'ano_mes'] = pd.to_datetime(df['data_inicio']).dt.to_period('M')
df

,data_inicio,data_fim,ano_mes,valor,base_legal
0,2022-01-01,2022-12-31,2022-01,31.97,"​Comunicado DICAR-89/21, de 17-12-2021"
1,2021-01-01,2021-12-31,2021-01,29.09,"Comunicado DICAR-86/20, de 17-12-2020"
2,2020-01-01,2020-12-31,2020-01,27.61,"​Comunicado DICAR-83/19, de 18-12-2019"
3,2019-01-01,2019-12-31,2019-01,26.53,"Comunicado DA-89/18, de 18-12-2018"
4,2018-01-01,2018-12-31,2018-01,25.70,"Comunicado DA-96/17, de 20-12-2017"
5,2017-01-01,2017-12-31,2017-01,25.07,"Comunicado DA-98/16, de 19-12-2016"
6,2016-01-01,2016-12-31,2016-01,23.55,"Comunicado DA-98/15, de 17-12-2015"
7,2015-01-01,2015-12-31,2015-01,21.25,"Comunicado DA-80/14, de 16-12-2014"
8,2014-01-01,2014-12-31,2014-01,20.14,"Comunicado DA-75/13, de 18-12-2013"
9,2013-01-01,2013-12-31,2013-01,19.37,"Comunicado DA-90/12, de 18-12-2012"
10,2012-01-01,2012-12-31,2012-01,18.44,"Comunicado DA-87/11, de 19-12-2011"
11,2011-01-01,2011-12-31,2011-01,17.45,"Comunicado DA-88/10, de 17-12-2010"
12,2010-01-01,2010-12-31,2010-01,16.42,"Comunicado DA-55/09, de 17-12-2009"
13,2009-01-01,2009-12-31,2009-01,15.85,"Comunicado DA-52/08, de 17-12-2008"
14,2008-01-01,2008-12-31,2008-01,14.88,"Comunicado DA-53/07, de 19-12-2007"
15,2007-01-01,2007-12-31,2007-01,14.23,"Comunicado DA-51/06, de 20-12-2006"
16,2006-01-01,2006-12-31,2006-01,13.93,"Comunicado DA-57/05, de 20-12-2005"
17,2005-01-01,2005-12-31,2005-01,13.30,"Comunicado DA-50/04, de 20-12-2004"
18,2004-01-01,2004-12-31,2004-01,12.49,"Comunicado DA-39/03, de 18-12-2003"
19,2003-01-01,2003-12-31,2003-01,11.49,"Comunicado DA-32/02, de 18-12-2002"
20,2002-01-01,2002-12-31,2002-01,10.52,"Comunicado DA-27/01, de 26-12-2001"
21,2001-01-01,2001-12-31,2001-01,9.83,NaN
22,2000-01-01,2000-12-31,2000-01,9.27,NaN
23,1999-01-01,1999-12-31,1999-01,8.51,NaN
24,1998-01-01,1998-12-31,1998-01,8.37,NaN
25,1997-01-01,1997-12-31,1997-01,7.93,NaN

In [30]:
df.dtypes

data_inicio    datetime64[ns]
data_fim       datetime64[ns]
ano_mes             period[M]
valor                 float64
base_legal             object
dtype: object